FROM python:3.11-slim
WORKDIR /app/backend
COPY ./backend/ /app/backend/
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
